### ISSUE TITLE
Field name "block" conflicts with argument `block` in `copy` function of DTO class

### ISSUE THREAD

**Issue by EliMadDev** [ermadmi78/kobby#18]
`someDTo.copy(block: someLambdaToRun`
...
`...Builder().also {
    it.block = block
    it.otherParam = otherParam...`
...
` .apply(block).let {`

so paramter "block" should be 'block'

**Comment by ermadmi78** [comment]
Reproduced. Will rename "block" to "__block" to reduce the likelihood of a name collision.

**Comment by ermadmi78** [comment]
`this` keyword will be added to fix the problem

`...Builder().also { it.block = block it.otherParam = otherParam...`
will be replaced to
`...Builder().also { it.block = this.block it.otherParam = this.otherParam...`

**Comment by ermadmi78** [comment]
Fixed in release 1.3.1 in scope of [#17](https://github.com/ermadmi78/kobby/issues/17) issue.
